"""Add subchain_id to stores

Revision ID: ee8c217296b3
Revises: ed09cf3cea79
Create Date: 2025-04-23 05:23:03.056185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee8c217296b3'
down_revision: Union[str, None] = 'ed09cf3cea79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shopping_cart_id', table_name='shopping_cart')
    op.drop_table('shopping_cart')
    op.drop_index('ix_purchase_items_id', table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index('ix_purchases_id', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('ix_stores_chain_id', table_name='stores')
    op.drop_index('ix_stores_id', table_name='stores')
    op.drop_index('ix_stores_store_id', table_name='stores')
    op.drop_table('stores')
    op.drop_index('ix_store_products_id', table_name='store_products')
    op.drop_index('ix_store_products_item_code', table_name='store_products')
    op.drop_index('ix_store_products_store_id', table_name='store_products')
    op.drop_table('store_products')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_families_id', table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('families_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='families_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='families_pkey'),
    sa.UniqueConstraint('name', name='families_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_families_id', 'families', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_products_name', 'products', ['name'], unique=True)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name='users_family_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('store_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manufacturer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manufacturer_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unit_quantity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity_in_package', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discounted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='store_products_pkey')
    )
    op.create_index('ix_store_products_store_id', 'store_products', ['store_id'], unique=False)
    op.create_index('ix_store_products_item_code', 'store_products', ['item_code'], unique=False)
    op.create_index('ix_store_products_id', 'store_products', ['id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chain_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chain_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stores_pkey')
    )
    op.create_index('ix_stores_store_id', 'stores', ['store_id'], unique=False)
    op.create_index('ix_stores_id', 'stores', ['id'], unique=False)
    op.create_index('ix_stores_chain_id', 'stores', ['chain_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('purchases_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchased_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='purchases_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchases_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_purchases_id', 'purchases', ['id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='purchase_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name='purchase_items_purchase_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchase_items_pkey')
    )
    op.create_index('ix_purchase_items_id', 'purchase_items', ['id'], unique=False)
    op.create_table('shopping_cart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchased', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name='shopping_cart_family_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='shopping_cart_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='shopping_cart_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shopping_cart_pkey')
    )
    op.create_index('ix_shopping_cart_id', 'shopping_cart', ['id'], unique=False)
    # ### end Alembic commands ###
